apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3   # scale as needed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # allow 1 pod to be down during update
      maxSurge: 2         # start 2 extra pods during rollout for faster replacement
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: project12acr.azurecr.io/myapp:latest   # pipeline replaces tag
        imagePullPolicy: IfNotPresent   # speeds up deploys in dev (doesn't pull if already present)
        ports:
        - containerPort: 80             # Nginx default
        env:
        - name: NODE_ENV
          value: "production"

        # Faster probes (dev-optimized)
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3   # start checking sooner
          periodSeconds: 3         # check more frequently
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 6
          periodSeconds: 5
          failureThreshold: 2
