apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: LoadBalancer     # Exposes externally via Azure Load Balancer
  selector:
    app: myapp
  ports:
  - port: 80             # external port
    targetPort: 80       # forwards traffic to Nginx in the pod
    protocol: TCP